#!/usr/bin/env bash

for file; do
    # read $lines array
    mapfile -t lines < "$file"

    # make sure the input ends with a clean blank column where we add the final answer to the grand total
    for ((index = 0; index < ${#lines[@]}; index++)); do
        lines[index]+=' '
    done

    # split last line into separate $operators string
    operators=${lines[-1]}
    unset 'lines[-1]'

    let grand_total=0
    let answer=0
    for ((index = 0; index < ${#operators}; index++)); do
        # process operator (if any)
        operator=${operators:index:1}
        if [[ $operator == '*' ]]; then
            let answer=1
            current_operator=$operator
        elif [[ $operator == '+' ]]; then
            let answer=0
            current_operator=$operator
        fi

        # assemble number (if any)
        number=''
        for line in "${lines[@]}"; do
            digit=${line:index:1}
            if [[ $digit =~ [0-9] ]]; then
                number+=$digit
            fi
        done

        # apply number with operator to answer, or add answer to grand total if this is the blank separator column
        if [[ $number != '' ]]; then
            if [[ $current_operator == '+' ]]; then
                let answer+=number
            else
                let answer*=number
            fi
        else
            let grand_total+=answer
        fi
    done

    printf '%s: grand total is %d\n' "$file" "$grand_total"
done
