#!/usr/bin/env bash

# change to length=2 for part 1
length=12

for file; do
    let output=0
    while IFS= read line; do
        rest=$line
        joltage=
        for ((nth=1; nth<=length; nth++)); do
            # $candidates = all but the last $nth-1 digits of $rest
            if ((nth == length)); then candidates=$rest; else candidates=${rest::-(length-nth)}; fi
            for digit in {9..1}; do
                if [[ $candidates = *$digit* ]]; then
                    # we found a digit, add it to the joltage and remove everything up to it from the rest of the line
                    joltage="$joltage$digit"
                    rest=${rest#*$digit}
                    break
                fi
            done
        done
        let output+=joltage
    done < "$file"
    printf '%s: %d\n' "$file" "$output"
done
