#!/usr/bin/env bash

for file; do
    let output=0
    while IFS= read line; do
        rest=$line
        joltage=
        for nth in {1..12}; do
            # $candidates = all but the last $nth-1 digits of $rest
            if ((nth == 12)); then candidates=$rest; else candidates=${rest::-(12-nth)}; fi
            for digit in {9..1}; do
                if [[ $candidates = *$digit* ]]; then
                    joltage="$joltage$digit"
                    rest=${rest#*$digit}
                    break
                fi
            done
        done
        let output+=joltage
    done < "$file"
    printf '%s: %d\n' "$file" "$output"
done
